---
abstract: 'Warns and dies noisily with stack backtraces'
author:
  - 'haarg - Graham Knop (cpan:HAARG) <haarg@haarg.org>'
build_requires:
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel::Confess
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Scalar::Util: 0
  perl: v5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Devel-Confess
  license: http://dev.perl.org/licenses/
  repository: git://github.com/haarg/Devel-Confess
version: 0.003001
